on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

name: build-oracle

jobs:
  oracle:
    name: Oracle tests.
    uses: php-forge/actions/.github/workflows/phpunit-database.yml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      concurrency-group: oracle-${{ github.ref }}
      database-env: |
        {
          "ORACLE_DATABASE": "yiitest",
          "ORACLE_PASSWORD": "root",
        }
      database-health-cmd: "healthcheck.sh"
      database-health-retries: 10
      database-image: gvenzl/oracle-free
      database-port: 1521
      database-type: oci
      database-versions: '["23"]'
      enable-concurrency: true
      extensions: pdo, pdo_oci
      os: '["ubuntu-latest"]'
      php-version: '["8.4"]'
      phpunit-group: oci
