on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

name: build

jobs:
  phpunit:
    uses: php-forge/actions/.github/workflows/phpunit.yml@fix-mini-31
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      composer-command: |
        composer require yiisoft/yii2:22.0.x-dev --prefer-dist --no-progress --no-interaction --no-scripts --ansi
      concurrency-group: phpunit-${{ github.workflow }}-${{ github.ref }}
      extensions: pdo, pdo_sqlite
      phpunit-group: sqlite
  phpunit-compatibility:
    uses: php-forge/actions/.github/workflows/phpunit.yml@mfix-mini-31
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      concurrency-group: compatibility-${{ github.workflow }}-${{ github.ref }}
      extensions: pdo, pdo_sqlite
      phpunit-group: sqlite
