on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

name: build-pgsql

jobs:
  pgsql:
    name: PostgreSQL tests.
    uses: php-forge/actions/.github/workflows/phpunit-database.yml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      concurrency-group: pgsql-${{ github.ref }}
      database-env: |
        {
          "POSTGRES_DB": "yiitest",
          "POSTGRES_USER": "root",
          "POSTGRES_PASSWORD": "root",
        }
      database-health-cmd: "pg_isready -U postgres"
      database-health-retries: 3
      database-image: postgres
      database-port: 5432
      database-type: pgsql
      database-versions: '["15", "16", "17"]'
      enable-concurrency: true
      extensions: pdo, pdo_pgsql
      os: '["ubuntu-latest"]'
      php-version: '["8.4"]'
      phpunit-group: pgsql
