on:
  - pull_request
  - push

name: build

jobs:
  mysql:
    name: MySQL tests.
    uses: php-forge/actions/.github/workflows/phpunit-database.yml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      concurrency-group: mysql-${{ github.ref }}
      database-env: |
        {
          "MYSQL_DATABASE": "yiitest",
          "MYSQL_ROOT_PASSWORD": "root",
        }
      database-health-cmd: "mysqladmin ping"
      database-health-retries: 3
      database-image: mysql
      database-port: 3306
      database-type: mysql
      database-versions: '["8.0", "8.4", "latest"]'
      enable-concurrency: true
      extensions: pdo, pdo_mysql
      group-phpunit: mysql
      os: '["ubuntu-latest"]'
      php-versions: '["8.4"]'
