on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

name: mutation test

jobs:
  mutation:
    uses: php-forge/actions/.github/workflows/infection.yml@main
    with:
      command-options: --static-analysis-tool=phpstan --threads=2 --ignore-msi-with-no-mutations --only-covered
      composer-command: |
        composer require --dev infection/infection:dev-master
        vendor/bin/phpstan --configuration=phpstan.neon analyse
    secrets:
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
