on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

name: mutation test

jobs:
  mutation:
    uses: php-forge/actions/.github/workflows/infection.yml@main
    with:
      command: phpstan-mutant-killer-infection-runner
      composer-command: composer require --dev phpstan/mutant-killer-infection-runner
    secrets:
      STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
