on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

name: static analysis

jobs:
  phpstan:
    uses: php-forge/actions/.github/workflows/phpstan.yml@main
    with:
      composer-command: |
        composer require yiisoft/yii2:^2.0.49 --prefer-dist --no-progress --no-interaction --no-scripts --ansi
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.4']
